import { Leaf } from "lucide-react";
import { useState, type FormEvent, type ReactNode } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { forgotPassword, login, register, resetPassword } from "../services/authService";
import { getApiMessage } from "../services/axiosClient";

export function LoginPage() { const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: "", password: "" }); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); try { const auth = await login(form); const target = auth.user.role === "ADMIN" ? "/admin" : ((location.state as { from?: string } | null)?.from || "/"); navigate(target); } catch (error) { setMessage(getApiMessage(error)); } finally { setLoading(false); } } return <AuthShell title="Mừng bạn trở lại" subtitle="Đăng nhập để theo dõi đơn hàng và lịch chăm sóc."><form className="auth-form" onSubmit={submit}><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Mật khẩu<input required type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><div className="auth-inline"><Link to="/forgot-password">Quên mật khẩu?</Link></div>{message && <p className="notice error">{message}</p>}<button disabled={loading} className="wide">{loading ? "Đang đăng nhập..." : "Đăng nhập"}</button><p>Chưa có tài khoản? <Link to="/register">Đăng ký</Link></p><small>Tài khoản mẫu: customer@tiemreu.vn / Customer@123</small></form></AuthShell>; }
export function RegisterPage() { const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", phone: "", password: "" }); const [message, setMessage] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); try { await register(form); navigate("/"); } catch (error) { setMessage(getApiMessage(error)); } } return <AuthShell title="Gia nhập góc xanh" subtitle="Lưu sản phẩm yêu thích và nhận lịch chăm sóc sau mua."><form className="auth-form" onSubmit={submit}><label>Họ tên<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Số điện thoại<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Mật khẩu<input required minLength={6} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label>{message && <p className="notice error">{message}</p>}<button className="wide">Tạo tài khoản</button><p>Đã có tài khoản? <Link to="/login">Đăng nhập</Link></p></form></AuthShell>; }
export function ForgotPasswordPage() { const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [token, setToken] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); try { const response = await forgotPassword(email); setMessage(response.message); setToken(response.developmentToken || ""); } catch (error) { setMessage(getApiMessage(error)); } } return <AuthShell title="Khôi phục mật khẩu" subtitle="Nhập email đã đăng ký để tạo liên kết có hiệu lực trong một giờ."><form className="auth-form" onSubmit={submit}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>{message && <p className="notice">{message}</p>}{token && <Link className="button wide" to={`/reset-password?token=${token}`}>Mở link reset local</Link>}<button className="wide">Gửi yêu cầu</button><p><Link to="/login">Quay lại đăng nhập</Link></p></form></AuthShell>; }
export function ResetPasswordPage() { const navigate = useNavigate(); const location = useLocation(); const token = new URLSearchParams(location.search).get("token") || ""; const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) return setMessage("Mật khẩu xác nhận chưa khớp"); try { const response = await resetPassword(token, password); setMessage(response.message); setTimeout(() => navigate("/login"), 900); } catch (error) { setMessage(getApiMessage(error)); } } return <AuthShell title="Đặt mật khẩu mới" subtitle="Liên kết chỉ dùng được một lần và hết hạn sau một giờ."><form className="auth-form" onSubmit={submit}><label>Mật khẩu mới<input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Xác nhận mật khẩu<input required minLength={6} type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{message && <p className="notice">{message}</p>}<button disabled={!token} className="wide">Đổi mật khẩu</button><p><Link to="/forgot-password">Yêu cầu link khác</Link></p></form></AuthShell>; }
function AuthShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <main className="auth-page"><section className="auth-visual"><img src="/tiem_reu_cover_photo.png" alt="Tiệm Rêu" /><div><Leaf /><h2>Chạm vào một mảng xanh.</h2></div></section><section className="auth-panel"><Link to="/" className="brand"><img src="/logo.png" alt="" /><span>TIỆM RÊU</span></Link><div><span className="eyebrow">Tài khoản Tiệm Rêu</span><h1>{title}</h1><p>{subtitle}</p>{children}</div></section></main>; }
