import { ArrowRight, CalendarDays, Heart, Leaf, MessageCircle, Send } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Loading } from "../components/Loading";
import { currentUser } from "../services/authService";
import { getApiMessage } from "../services/axiosClient";
import { addBlogComment, addBlogReply, getBlog, getBlogComments, getBlogLikes, getBlogs, toggleBlogLike } from "../services/contentService";
import type { BlogComment, BlogLike, BlogPost } from "../types/content";
import { formatDate } from "../utils/format";

export function BlogPage() { const [posts, setPosts] = useState<BlogPost[] | null>(null); useEffect(() => { getBlogs().then(setPosts); }, []); return <main className="page container"><div className="page-title"><span className="eyebrow">Góc xanh</span><h1>Chuyện cây, chuyện rêu</h1><p>Kinh nghiệm chăm sóc và những câu chuyện nhỏ quanh terrarium.</p></div>{!posts ? <Loading /> : <div className="blog-grid">{posts.map((post) => <article key={post.id}><Link to={`/blog/${post.slug}`}><img src={post.thumbnail || "/about_us_bg.png"} alt={post.title} /></Link><div><span className="eyebrow">{post.category || "Terrarium"}</span><h2><Link to={`/blog/${post.slug}`}>{post.title}</Link></h2><p>{post.intro}</p><span><CalendarDays /> {formatDate(post.publishedAt)}</span><Link className="text-link" to={`/blog/${post.slug}`}>Đọc bài <ArrowRight /></Link></div></article>)}</div>}</main>; }
export function BlogDetailPage() {
  const { slug = "" } = useParams(); const navigate = useNavigate();
  const [post, setPost] = useState<BlogPost | null>(null); const [likes, setLikes] = useState<BlogLike>({ likesCount: 0, liked: false });
  const [comments, setComments] = useState<BlogComment[]>([]); const [content, setContent] = useState("");
  const [replyInputs, setReplyInputs] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([getBlog(slug), getBlogLikes(slug), getBlogComments(slug)]).then(([article, likeData, commentData]) => { setPost(article); setLikes(likeData); setComments(commentData); }).catch((error) => setMessage(getApiMessage(error))); }, [slug]);
  async function like() { if (!currentUser()) return navigate("/login", { state: { from: `/blog/${slug}` } }); try { setLikes(await toggleBlogLike(slug)); } catch (error) { setMessage(getApiMessage(error)); } }
  async function comment(event: FormEvent) { event.preventDefault(); if (!currentUser()) return navigate("/login", { state: { from: `/blog/${slug}` } }); if (!content.trim()) return; try { const created = await addBlogComment(slug, content); setComments((value) => [created, ...value]); setContent(""); } catch (error) { setMessage(getApiMessage(error)); } }
  async function reply(commentId: string) { if (!currentUser()) return navigate("/login", { state: { from: `/blog/${slug}` } }); const text = replyInputs[commentId]?.trim(); if (!text) return; try { const created = await addBlogReply(commentId, text); setComments((value) => value.map((item) => item.id === commentId ? { ...item, replies: [...item.replies, created] } : item)); setReplyInputs((value) => ({ ...value, [commentId]: "" })); } catch (error) { setMessage(getApiMessage(error)); } }
  if (!post) return <main className="page container">{message ? <p className="notice error">{message}</p> : <Loading />}</main>;
  return <main className="article-page"><header><span className="eyebrow"><Leaf /> {post.category || "Góc xanh"}</span><h1>{post.title}</h1><p>{post.intro}</p><time>{formatDate(post.publishedAt)}</time></header>{post.thumbnail && <img className="article-cover" src={post.thumbnail} alt={post.title} />}<article>{post.content?.split("\n").map((paragraph, index) => <p key={`${paragraph}-${index}`}>{paragraph}</p>)}</article><section className="article-social"><button className={likes.liked ? "selected" : "outline"} onClick={like}><Heart fill={likes.liked ? "currentColor" : "none"} /> {likes.likesCount} lượt thích</button><h2><MessageCircle /> Bình luận ({comments.length})</h2><form className="comment-form" onSubmit={comment}><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Chia sẻ cảm nhận của bạn..." /><button><Send /> Gửi bình luận</button></form>{message && <p className="notice">{message}</p>}<div className="comment-list">{comments.map((item) => <article key={item.id}><div><b>{item.customer.name}</b><small>{formatDate(item.createdAt)}</small></div><p>{item.content}</p>{item.replies.map((replyItem) => <div className="blog-reply" key={replyItem.id}><b>{replyItem.user.name}{replyItem.adminReply && " · Tiệm Rêu"}</b><p>{replyItem.content}</p></div>)}<div className="reply-form"><input value={replyInputs[item.id] || ""} onChange={(event) => setReplyInputs((value) => ({ ...value, [item.id]: event.target.value }))} placeholder="Trả lời bình luận..." /><button type="button" onClick={() => reply(item.id)}>Trả lời</button></div></article>)}</div></section></main>;
}
