import { CheckCircle2, Ticket } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useCart } from "../context/CartContext";
import { currentUser } from "../services/authService";
import { createOrder, validateVoucher } from "../services/commerceService";
import { getApiMessage } from "../services/axiosClient";
import type { Order, VoucherValidation } from "../types/commerce";
import { formatMoney } from "../utils/format";

export function CheckoutPage() {
  const { items, subtotal, clear } = useCart(); const navigate = useNavigate(); const user = currentUser();
  const [form, setForm] = useState({ name: user?.name || "", phone: user?.phone || "", email: user?.email || "", province: "", district: "", ward: "", fullAddress: "" });
  const [voucherCode, setVoucherCode] = useState(""); const [voucher, setVoucher] = useState<VoucherValidation | null>(null);
  const [shippingMethod, setShippingMethod] = useState("GHN_STANDARD"); const [paymentMethod, setPaymentMethod] = useState("COD");
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [created, setCreated] = useState<Order | null>(null);
  if (!items.length && !created) return <main className="page container"><div className="empty-state"><h2>Không có sản phẩm để thanh toán</h2><Link className="button" to="/products">Chọn sản phẩm</Link></div></main>;
  async function applyVoucher() { try { const result = await validateVoucher(voucherCode, items.map((item) => ({ productId: item.product.id, quantity: item.quantity, variants: item.variants }))); setVoucher(result); setMessage(result.valid ? "Voucher hợp lệ" : result.error || "Voucher không hợp lệ"); } catch (error) { setMessage(getApiMessage(error)); } }
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const order = await createOrder({ items: items.map((item) => ({ productId: item.product.id, quantity: item.quantity, variants: item.variants })), shippingInfo: form, shippingMethod, paymentMethod, discountCode: voucher?.valid ? voucherCode : undefined }); setCreated(order); clear(); if (user) setTimeout(() => navigate(`/orders/${order.id}`), 1200); } catch (error) { setMessage(getApiMessage(error)); } finally { setLoading(false); } }
  if (created) return <main className="center-page"><div className="success-card"><CheckCircle2 /><h1>Đặt hàng thành công</h1><p>Mã đơn: <b>{created.orderNumber}</b></p><p>Tổng thanh toán: {formatMoney(created.total)}</p><Link className="button" to={`/orders/${created.id}?orderNumber=${created.orderNumber}`}>Xem đơn hàng</Link></div></main>;
  const shipping = shippingMethod === "GHN_STANDARD" ? 30000 : shippingMethod === "GHN_EXPRESS" ? 45000 : 60000;
  const total = subtotal + (voucher?.freeShipping ? 0 : shipping) - (voucher?.valid ? voucher.discountAmount : 0);
  return <main className="page container"><div className="page-title left"><span className="eyebrow">Thanh toán an toàn</span><h1>Thông tin nhận hàng</h1></div><form className="checkout-layout" onSubmit={submit}><div className="checkout-form"><section className="panel"><h2>Liên hệ & địa chỉ</h2><div className="form-grid"><label>Họ tên<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Số điện thoại<input required value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Tỉnh/Thành<input value={form.province} onChange={(event) => setForm({ ...form, province: event.target.value })} /></label><label>Quận/Huyện<input value={form.district} onChange={(event) => setForm({ ...form, district: event.target.value })} /></label><label>Phường/Xã<input value={form.ward} onChange={(event) => setForm({ ...form, ward: event.target.value })} /></label><label className="full">Địa chỉ chi tiết<textarea required value={form.fullAddress} onChange={(event) => setForm({ ...form, fullAddress: event.target.value })} /></label></div></section>
    <section className="panel"><h2>Vận chuyển</h2>{[["GHN_STANDARD", "GHN tiêu chuẩn · 30.000đ"], ["GHN_EXPRESS", "GHN nhanh · 45.000đ"], ["GRAB", "Hỏa tốc nội thành · 60.000đ"]].map(([value, label]) => <label className="radio-row" key={value}><input type="radio" checked={shippingMethod === value} onChange={() => setShippingMethod(value)} />{label}</label>)}</section>
    <section className="panel"><h2>Thanh toán</h2>{[["COD", "Thanh toán khi nhận hàng"], ["BANK_TRANSFER", "Chuyển khoản ngân hàng"], ["MOMO", "Ví MoMo (cần cấu hình cổng thanh toán)"]].map(([value, label]) => <label className="radio-row" key={value}><input type="radio" checked={paymentMethod === value} onChange={() => setPaymentMethod(value)} />{label}</label>)}</section></div>
    <aside className="order-summary"><h2>Đơn hàng</h2>{items.map((item) => <div key={item.key}><span>{item.product.name} × {item.quantity}</span><b>{formatMoney(item.unitPrice * item.quantity)}</b></div>)}<label className="voucher-input"><Ticket /><input value={voucherCode} onChange={(event) => setVoucherCode(event.target.value.toUpperCase())} placeholder="Mã voucher" /><button type="button" onClick={applyVoucher}>Áp dụng</button></label>{message && <p className={voucher?.valid ? "notice success" : "notice"}>{message}</p>}<hr /><div><span>Tạm tính</span><b>{formatMoney(subtotal)}</b></div><div><span>Vận chuyển</span><b>{voucher?.freeShipping ? "Miễn phí" : formatMoney(shipping)}</b></div>{voucher?.valid && <div><span>Giảm giá</span><b>-{formatMoney(voucher.discountAmount)}</b></div>}<div className="total"><span>Tổng cộng</span><strong>{formatMoney(total)}</strong></div><button disabled={loading} className="wide" type="submit">{loading ? "Đang tạo đơn..." : "Đặt hàng"}</button></aside></form></main>;
}
