import { CheckCircle2, Circle, Package, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { Loading } from "../components/Loading";
import { cancelOrder, getOrder } from "../services/commerceService";
import { getApiMessage } from "../services/axiosClient";
import type { Order } from "../types/commerce";
import { formatDate, formatMoney } from "../utils/format";

const steps = ["PENDING", "CONFIRMED", "PROCESSING", "SHIPPING", "DELIVERED"];
export function OrderDetailPage() { const { id = "" } = useParams(); const [query] = useSearchParams(); const [order, setOrder] = useState<Order | null>(null); const [message, setMessage] = useState(""); useEffect(() => { getOrder(id, query.get("orderNumber") || undefined).then(setOrder).catch((error) => setMessage(getApiMessage(error))); }, [id, query]); if (!order) return <main className="page container">{message || <Loading />}</main>; const activeIndex = steps.indexOf(order.status); return <main className="page container"><div className="order-detail-head"><div><span className="eyebrow">Chi tiết đơn hàng</span><h1>{order.orderNumber}</h1><p>Đặt lúc {formatDate(order.createdAt)}</p></div><span className={`status ${order.status.toLowerCase()}`}>{order.status}</span></div><div className="timeline">{steps.map((step, index) => <div className={index <= activeIndex ? "done" : ""} key={step}>{index < activeIndex ? <CheckCircle2 /> : index === activeIndex ? <Truck /> : <Circle />}<span>{step}</span></div>)}</div><div className="checkout-layout"><div><section className="panel"><h2>Sản phẩm</h2>{order.items.map((item) => <div className="order-line" key={item.id}><img src={item.productImage || "/logo.png"} alt="" /><div className="grow"><b>{item.productName}</b><span>Số lượng: {item.quantity}</span></div><strong>{formatMoney(item.price * item.quantity)}</strong></div>)}</section><section className="panel"><h2>Giao hàng</h2><p><Package /> {order.shippingInfo?.name} · {order.shippingInfo?.phone}</p><p>{order.shippingInfo?.fullAddress}, {order.shippingInfo?.ward}, {order.shippingInfo?.district}, {order.shippingInfo?.province}</p></section></div><aside className="order-summary"><h2>Thanh toán</h2><div><span>Tạm tính</span><b>{formatMoney(order.subtotal)}</b></div><div><span>Phí giao</span><b>{formatMoney(order.shippingFee)}</b></div><div><span>Giảm giá</span><b>-{formatMoney(order.discount)}</b></div><hr /><div className="total"><span>Tổng</span><strong>{formatMoney(order.total)}</strong></div><p>{order.paymentMethod} · {order.paymentStatus}</p>{["PENDING", "CONFIRMED"].includes(order.status) && <button className="outline danger" onClick={async () => setOrder(await cancelOrder(order.id))}>Hủy đơn</button>}</aside></div></main>; }
