import { Droplets, Heart, Leaf, Scissors, Star, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState, Loading } from "../components/Loading";
import { ProductCard } from "../components/ProductCard";
import { currentUser, me } from "../services/authService";
import { getCareItems, getFavorites, updateCare } from "../services/commerceService";
import type { UserInfo } from "../types/auth";
import type { Product } from "../types/catalog";
import type { CareItem } from "../types/commerce";
import { formatDate } from "../utils/format";

export function ProfilePage() { const [user, setUser] = useState<UserInfo | null>(() => currentUser()); const [favorites, setFavorites] = useState<Product[] | null>(null); const [care, setCare] = useState<CareItem[] | null>(null); useEffect(() => { me().then(setUser); getFavorites().then(setFavorites); getCareItems().then(setCare); }, []); if (!user) return <main className="page container"><Loading /></main>; async function careAction(id: string, action: string) { const updated = await updateCare(id, action); setCare((current) => current?.map((item) => item.id === id ? updated : item) || []); } return <main className="page container"><div className="profile-hero"><div className="avatar"><UserRound /></div><div><span className="eyebrow">Tài khoản khách hàng</span><h1>{user.name}</h1><p>{user.email} · {user.phone}</p></div><div className="loyalty-card"><Star /><b>{user.loyaltyPoints} điểm</b><span>Hạng {user.loyaltyTier}</span></div></div><div className="account-tabs"><Link to="/orders">Đơn hàng</Link><a href="#favorites">Yêu thích</a><a href="#care">Lịch chăm sóc</a></div><section id="favorites" className="section compact"><div className="section-heading"><h2><Heart /> Sản phẩm yêu thích</h2></div>{favorites === null ? <Loading /> : favorites.length ? <div className="product-grid">{favorites.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <EmptyState title="Chưa có sản phẩm yêu thích" />}</section><section id="care" className="section compact"><div className="section-heading"><h2><Leaf /> Lịch chăm sóc</h2></div>{care === null ? <Loading /> : care.length ? <div className="care-list">{care.map((item) => <article key={item.id}><div><b>{item.productName}</b><p>{item.careSchedule}</p><span>Lần tưới gần nhất: {formatDate(item.lastWateredAt)}</span><span>Lịch tiếp theo: {formatDate(item.nextWateringAt)}</span></div><div><button onClick={() => careAction(item.id, "water")}><Droplets /> Đã tưới</button><button className="outline" onClick={() => careAction(item.id, "prune")}><Scissors /> Đã tỉa</button></div></article>)}</div> : <EmptyState title="Chưa có lịch chăm sóc" description="Lịch sẽ được tạo khi đơn hàng của bạn được giao thành công." />}</section></main>; }
