import { Plus } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { campaigns, saveCampaign, type Campaign } from "../../services/adminService";
import { getApiMessage } from "../../services/axiosClient";
import { formatMoney } from "../../utils/format";
import { AdminHead } from "./AdminDashboard";

const localDate = (days: number) => { const date = new Date(Date.now() + days * 86400000); return date.toISOString().slice(0, 16); };
export function AdminVouchers() { const [items, setItems] = useState<Campaign[]>([]); const [form, setForm] = useState({ code: "", type: "PERCENTAGE", value: 10, minOrderAmount: 0, maxDiscountAmount: 100000, startsAt: localDate(0), expiresAt: localDate(30), usageLimit: 100, status: "ACTIVE", description: "" }); const [message, setMessage] = useState(""); const load = () => campaigns().then(setItems); useEffect(() => { load(); }, []); async function submit(event: FormEvent) { event.preventDefault(); try { await saveCampaign({ ...form, startsAt: new Date(form.startsAt).toISOString(), expiresAt: new Date(form.expiresAt).toISOString(), applicableTo: "ALL", applicableIds: [] }); setMessage("Đã tạo voucher"); await load(); } catch (error) { setMessage(getApiMessage(error)); } } return <><AdminHead title="Voucher" description="Usage chỉ tăng sau khi đơn được tạo thành công." /><div className="admin-two-columns"><form className="panel" onSubmit={submit}><h2>Tạo chương trình</h2><div className="form-grid"><label>Mã<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} /></label><label>Loại<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option>PERCENTAGE</option><option>FIXED</option><option>FREE_SHIPPING</option></select></label><label>Giá trị<input type="number" value={form.value} onChange={(event) => setForm({ ...form, value: Number(event.target.value) })} /></label><label>Đơn tối thiểu<input type="number" value={form.minOrderAmount} onChange={(event) => setForm({ ...form, minOrderAmount: Number(event.target.value) })} /></label><label>Bắt đầu<input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} /></label><label>Kết thúc<input type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} /></label><label className="full">Mô tả<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>{message && <p className="notice">{message}</p>}<button><Plus /> Tạo voucher</button></form><div className="panel"><h2>Chương trình hiện có</h2>{items.map((item) => <div className="manage-row voucher-row" key={item.id}><div><b>{item.code}</b><span>{item.type} · {item.type === "PERCENTAGE" ? `${item.value}%` : formatMoney(item.value)}</span><small>Đã dùng {item.usageCount}/{item.usageLimit || "∞"} · {item.status}</small></div></div>)}</div></div></>; }
